# Generated by Django 2.0.2 on 2022-05-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_piso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Del Piso')),
                ('num_piso', models.IntegerField(blank=True, null=True, verbose_name='Numero Piso')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Piso')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
                'ordering': ['num_piso'],
            },
        ),
    ]
