# Generated by Django 2.0.2 on 2022-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_auto_20220525_1948'),
        ('piso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piso',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete='cascade', to='sucursales.Sucursal'),
            preserve_default=False,
        ),
    ]
