# Generated by Django 2.0.2 on 2022-06-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piso', '0002_piso_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.Sucursal'),
        ),
    ]
