# Generated by Django 2.0.2 on 2022-05-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='email',
            new_name='estado',
        ),
    ]
