# Generated by Django 2.0.2 on 2022-05-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_auto_20220525_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
