# Generated by Django 2.0.2 on 2022-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficina', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre oficina')),
                ('capacidad_oficina', models.IntegerField(blank=True, null=True, verbose_name='Capacidad de la oficna')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'oficina',
                'verbose_name_plural': 'oficinas',
                'ordering': ['nombre_oficina'],
            },
        ),
    ]
