# Generated by Django 2.0.2 on 2022-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='capacidad_oficina',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Capacidad de la oficna'),
        ),
    ]
