# Generated by Django 2.0.2 on 2022-05-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_oficina_piso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficina',
            options={'ordering': ['nombre_oficina'], 'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
    ]
