# Generated by Django 2.0.2 on 2022-06-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_auto_20220531_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='piso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piso.Piso'),
        ),
    ]
