# Generated by Django 2.0.2 on 2022-05-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroe',
            options={'ordering': ['nombre_heroe'], 'verbose_name': 'Heroe', 'verbose_name_plural': 'Heroes'},
        ),
        migrations.RenameField(
            model_name='heroe',
            old_name='nombe_heroe',
            new_name='nombre_heroe',
        ),
    ]
