# Generated by Django 2.0.2 on 2022-05-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0002_auto_20220526_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroe',
            options={'ordering': ['nombe_heroe'], 'verbose_name': 'Heroe', 'verbose_name_plural': 'Heroes'},
        ),
        migrations.RenameField(
            model_name='heroe',
            old_name='nombre_heroe',
            new_name='nombe_heroe',
        ),
    ]
