# Generated by Django 2.0.2 on 2022-06-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0003_auto_20220531_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroe',
            options={'ordering': ['nombre_heroe'], 'verbose_name': 'Heroe', 'verbose_name_plural': 'Heroes'},
        ),
        migrations.RenameField(
            model_name='heroe',
            old_name='nombre_heroe',
            new_name='nombre_heroe',
        ),
    ]
