# Generated by Django 2.0.2 on 2022-06-03 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piso', '0001_initial'),
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AddField(
            model_name='ingreso',
            name='caducidad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Horario Salida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Horario Ingreso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='piso',
            field=models.ForeignKey(default=1302, on_delete=django.db.models.deletion.CASCADE, to='piso.Piso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tipo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
