# Generated by Django 2.0.2 on 2022-06-03 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
        ('accesos', '0002_auto_20220602_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='lugar',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='parking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.Parking'),
            preserve_default=False,
        ),
    ]
