# Generated by Django 2.0.2 on 2022-06-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0004_ingreso_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Telefono'),
        ),
    ]
