# Generated by Django 2.0.2 on 2022-06-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0005_auto_20220602_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
