# Generated by Django 2.0.2 on 2022-06-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0006_auto_20220602_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada'),
        ),
    ]
