# Generated by Django 2.0.2 on 2022-05-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('motivo', models.CharField(blank=True, max_length=280, null=True, verbose_name='Motivo')),
                ('vehiculo', models.CharField(blank=True, max_length=30, null=True)),
                ('matricula', models.CharField(blank=True, max_length=10, null=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.Parking')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['nombre'],
            },
        ),
    ]
