# Generated by Django 2.0.2 on 2022-05-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1, null=True)),
                ('vip', models.IntegerField(blank=True, null=True)),
                ('colaborador', models.IntegerField(blank=True, null=True)),
                ('discapacitado', models.IntegerField(blank=True, null=True)),
                ('visita', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piso.Piso')),
            ],
            options={
                'verbose_name': 'Estacionamiento',
                'verbose_name_plural': 'Estacionamientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('disponibilidad', models.CharField(blank=True, default='Desocupado', max_length=100, null=True, verbose_name='Disponibilidad')),
                ('status', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.Estacionamiento')),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parkings',
                'ordering': ['lugar'],
            },
        ),
    ]
