# Generated by Django 2.0.2 on 2022-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='capacidad_sala_r',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='Capacidad'),
        ),
    ]
