# Generated by Django 2.0.2 on 2022-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piso', '0002_piso_sucursal'),
        ('sala', '0002_auto_20220526_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='piso',
            field=models.ForeignKey(default=1, on_delete='cascade', to='piso.Piso'),
            preserve_default=False,
        ),
    ]
