# Generated by Django 2.0.2 on 2022-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_salas_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='capacidad_sala_r',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Capacidad'),
        ),
    ]
