# Generated by Django 2.0.2 on 2022-05-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piso', '0002_piso_sucursal'),
        ('sala', '0004_auto_20220529_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salas',
            new_name='Sala',
        ),
    ]
