# Generated by Django 2.0.2 on 2022-06-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0006_auto_20220610_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='piso',
            field=models.ForeignKey(on_delete='cascade', to='piso.Piso'),
        ),
    ]
