# Generated by Django 2.0.2 on 2022-07-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piso', '0003_auto_20220610_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre sala de reunion')),
                ('capacidad_sala', models.IntegerField(blank=True, default=0, null=True, verbose_name='Capacidad')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('piso', models.ForeignKey(on_delete='cascade', to='piso.Piso')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nombre_sala'],
            },
        ),
    ]
